name: "Test and Build Website"

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Test and Build Website"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout main"
        uses: "actions/checkout@v5"

      - name: "Install Nix"
        uses: "DeterminateSystems/nix-installer-action@v20"

      - name: "Test and Build Website"
        run: |
          nix develop .#ci --command bash -c "npm ci && npm run check && npm run build"
